# Numpy Introduction

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

# What is an array?



An array is a data structure that stores a collection of elements (values or variables), each identified by at least one array index or key. Elements in an array are usually of the same data type, such as integers, strings, or other arrays, and are stored in contiguous memory locations. This allows for efficient access and manipulation of data.

In the context of programming:

- In Python, lists serve the purpose of arrays, but they are more versatile than traditional arrays as they can hold different types of data.
- In languages like C, C++, and Java, arrays have a fixed size and can only hold elements of the same data type.


In [3]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [18]:
a = np.arange(6) # one dimensional array
print(a)

a.shape

[0 1 2 3 4 5]


(6,)

In [17]:
# two dimensional array
a2 = a[np.newaxis, :] # add new axis at row position 0 (first row) 
print(a2)
a2.shape

[[0 1 2 3 4 5]]


(1, 6)

In [16]:
# two dimensional array
a3 = a[:, np.newaxis ] # add new axis at column position 0 (first column)
print(a3)
a3.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [23]:
# three dimensional array
a4 = a2[np.newaxis,:] # add new axis at row position 0 (first row)
print(a4)
a4.shape

[[[0 1 2 3 4 5]]]


(1, 1, 6)

# **Assignment:** why do we have 1D,2D or 3D arrays and where we need them in Data Science?

1D, 2D, and 3D arrays represent different dimensions of data, and each has its specific use cases in Data Science.

1. **1D Array**: A 1D array is a simple list or sequence of elements, similar to a vector. It's used when you're dealing with a single feature or attribute. For example, a list of ages or a list of prices.

2. **2D Array**: A 2D array, also known as a matrix, is essentially a table with rows and columns. This is the most common way to organize data for machine learning algorithms. Each row represents an instance (or sample), and each column represents a feature (or attribute). For example, a dataset of houses, where each row is a house and columns could be features like size, number of rooms, location, etc.

3. **3D Array (and higher dimensions)**: 3D arrays, also known as tensors, are often used in more complex scenarios, like images or videos. In an image, the dimensions could represent the width, height, and color channels (Red, Green, Blue). In a video, a 4D array could be used, with time being the additional dimension.

In Data Science, these different types of arrays allow us to work with different types of data, from simple lists of values (1D), to tabular data (2D), to more complex data like images or videos (3D and higher). They provide a way to organize, process, and analyze data in a structured manner.

---

# Creating Arrays in Numpy

In [24]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([(1,2,3,4,5,6,7),(8,9,10,11,12,13,14)])

In [42]:
a.dtype # data type of array elements
b.dtype

dtype('int32')

In [41]:
type(a) # type of array

numpy.ndarray

In [25]:
print(a)
a.shape


[1 2 3 4 5 6 7]


(7,)

In [26]:
print(b)
b.shape


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


(2, 7)

# Initialize an array

In [28]:
zeros = np.zeros((3,4)) # 3 rows, 4 columns
print(zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
zeros.dtype

dtype('float64')

In [30]:
ones = np.ones((2, 5)) # 2 rows, 5 columns
print(ones)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [38]:
ones.dtype

dtype('float64')

In [33]:
full_array = np.full((3, 4), 5) # 3 rows, 4 columns, filled with 5
print(full_array)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [39]:
full_array.dtype    

dtype('int32')

In [35]:
indentity_matrix = np.eye(5) # 5x5 identity matrix
print(indentity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Array Attributes

In [49]:
a.shape # shape of array a  

(7,)

In [44]:
len(a) # length of array

7

In [45]:
b.ndim # number of dimensions

2

In [47]:
a4.ndim # number of dimensions

3

In [50]:
a.size # number of elements in array

7

In [51]:
len(a) # length of array

7

In [52]:
b.size # number of elements in array

14

In [54]:
len(b) # length of array

2

# Basic Operations

In [55]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
b

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [57]:
g = a - b # subtract two arrays
print(g)

[[ 0  0  0  0  0  0  0]
 [-7 -7 -7 -7 -7 -7 -7]]


In [58]:
# Addition
h = a + b # add two arrays
print(h)

[[ 2  4  6  8 10 12 14]
 [ 9 11 13 15 17 19 21]]


In [60]:
# another method of addition
h1 = np.add(a,b) # add two arrays
print(h1)

[[ 2  4  6  8 10 12 14]
 [ 9 11 13 15 17 19 21]]


In [61]:
# multiplication
i = a * b # multiply two arrays
print(i)

[[ 1  4  9 16 25 36 49]
 [ 8 18 30 44 60 78 98]]


In [62]:
# Division
j = a / b # divide two arrays
print(j)

[[1.         1.         1.         1.         1.         1.
  1.        ]
 [0.125      0.22222222 0.3        0.36363636 0.41666667 0.46153846
  0.5       ]]


In [63]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [67]:
# square root of each element in array
k1 = np.sqrt(a) # square root of each element in array
print(k1)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131]


In [69]:
k2 = a ** 2 # square of each element in array
print(k2)

[ 1  4  9 16 25 36 49]
