# Numpy (Part-2)

In [2]:
import numpy as np

In [6]:
# create empty array
empty_array = np.empty((3, 4))
print(empty_array)
print("----------------------------------------")

print(empty_array[0])

[[8.60155099e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [1.11260619e-306 1.61590357e+184 4.21896273e-090 5.19412487e+170]
 [1.00525303e-047 1.65719424e-076 3.99910963e+252 4.50503329e-033]]
----------------------------------------
[8.60155099e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]


In [5]:
print(empty_array[2])

[1.00525303e-047 1.65719424e-076 3.99910963e+252 4.50503329e-033]


In [8]:
x = np.arange(23)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

In [11]:
# create array of even numbers upto 23
even_array = np.arange(0, 23, 2)
print(even_array)

[ 0  2  4  6  8 10 12 14 16 18 20 22]


In [12]:
# create array of odd numbers upto 23
odd_array = np.arange(1, 23, 2)
print(odd_array)

[ 1  3  5  7  9 11 13 15 17 19 21]


In [15]:
# specific difference between numbers
diff_array = np.arange(0, 11, 0.5)
print(diff_array)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10.  10.5]


In [19]:
# linspace function to create array of numbers with specific difference between them and specific number of elements

lin = np.linspace(0, 10, num=21) # 21 elements between 0 and 10 with equal difference between them 
print(lin)

[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [20]:
lin = np.linspace(0, -10, num=5)
print(lin)

[  0.   -2.5  -5.   -7.5 -10. ]


In [21]:
lin.dtype

dtype('float64')

In [26]:
# define the datatype of the array
x = np.arange(0, 10, dtype=np.float64)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# **Assignment:** what is the difference between int32, int64, or float 32, float 64?

`int32`, `int64`, `float32`, and `float64` are data types in programming that specify the kind of data and the amount of space they occupy in memory. Here's what each of them means:

1. **int32**: This is a 32-bit integer data type. It can store integer values from -2,147,483,648 to 2,147,483,647.

2. **int64**: This is a 64-bit integer data type. It can store integer values from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807. It's used when the values to be stored are larger than what `int32` can hold.

3. **float32**: This is a 32-bit floating-point data type. It can store real numbers, providing up to 6-7 decimal digits of precision.

4. **float64**: This is a 64-bit floating-point data type. It can store real numbers, providing up to 15-16 decimal digits of precision. It's used when higher precision is needed.

In the context of data science and machine learning, choosing between these data types is a trade-off between the precision of the data and the memory used to store it. Higher precision data types like `int64` and `float64` use more memory but can represent values more accurately, while lower precision data types like `int32` and `float32` use less memory but may lose some precision.

In [30]:
# define the datatype of the array
x = np.arange(0, 22.6, 1.5, dtype=np.int64)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
      dtype=int64)

In [31]:
# sorting an array
x = np.array([1, 5, 3, 2, 4])
print(x)

[1 5 3 2 4]


In [33]:
x = np.sort(x)
x

array([1, 2, 3, 4, 5])

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [35]:
# concatenate two arrays
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Concatenate 2D arrays

In [40]:
x = np.array([[1,2],[3,4]]) # 2 x 2 array 
y = np.array([[5,6]]) # 1 x 2 array

In [41]:
x

array([[1, 2],
       [3, 4]])

In [42]:
y

array([[5, 6]])

In [44]:
# concatenate 2D array
z = np.concatenate((x,y))
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
z = np.concatenate((x,y), axis=0) # concatenate along rows (axis=0)
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [46]:
# concatenate 2D array
w = np.array([[1,2],[3,4]]) # 2 x 2 array
x = np.array([[5,6],[7,8]]) # 2 x 2 array

z1 = np.concatenate((w,x), axis=1) # concatenate along columns (axis=1)
z1


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [47]:
z1 = np.concatenate((w,x), axis=0)
z1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
z1.ndim # number of dimensions

2

In [50]:
# create 3D array

array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [54]:
array_example.ndim # number of dimensions

3

In [53]:
len(array_example) # length of the array

3

In [56]:
array_example.size  # total number of elements in the array

24

In [57]:
array_example.dtype # datatype of the array

dtype('int32')

In [58]:
array_example.shape # shape of the array (3 x 2 x 4) 3 arrays of 2 rows and 4 columns

(3, 2, 4)

In [63]:
# create 3D array of size (3,1,4)

a1 = np.array([[[1,2,3,4]],[[5,6,7,8]],[[9,10,11,12]]])
a1

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [64]:
a1.ndim # number of dimensions

3

In [65]:
a1.shape # shape of the array (3,1,4)

(3, 1, 4)

In [67]:
a1

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [68]:
# reshape the array a1
a2 = a1.reshape(3,1,4)
a2

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

In [69]:
# create a 1D array
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [70]:
a.shape

(10,)

In [85]:
# convert into 2D array
b = a[np.newaxis, :]# add new axis at row position
b.shape # 1 x 10 array


(1, 10)

In [84]:
b

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [86]:
c = a[:, np.newaxis] # add new axis at column position
c.shape # 10 x 1 array

(10, 1)

In [87]:
c # 10 x 1 array

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# Indexing and Slicing

In [88]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
a[2] # 3rd element

3

In [90]:
a[2:5] # 3rd to 5th element

array([3, 4, 5])

In [91]:
a[-4:] # last 4 elements

array([ 7,  8,  9, 10])

In [92]:
a[-4:-2] # last 4th and 3rd elements 

array([7, 8])

In [93]:
a[3:] # 4th element to last element

array([ 4,  5,  6,  7,  8,  9, 10])

In [98]:
b = np.array([[1,2,3,4],[6,7,8,9], [11,12,13,14]])
b

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14]])

In [100]:
b[0] # 1st row of the array b

array([1, 2, 3, 4])

In [101]:
b[b<5] # elements of array b less than 5

array([1, 2, 3, 4])

In [102]:
b[b % 2 == 0] # even elements of array b  

array([ 2,  4,  6,  8, 12, 14])

In [103]:
# use two conditions
b[(b > 2) & (b < 11)] # elements of array b greater than 2 and less than 11

array([3, 4, 6, 7, 8, 9])

In [104]:
# use three conditons and filter the arrays
b[(b > 2) & (b < 11) & (b % 2 == 0)] # elements of array b greater than 2 and less than 11 and even numbers 

array([4, 6, 8])

In [105]:
b[(b>5) | (b<10)] # elements of array b greater than 5 or less than 10


array([ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14])